# Generated by Django 5.1.6 on 2025-02-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='chama_id',
            new_name='chama',
        ),
    ]
