# Generated by Django 5.1.6 on 2025-02-12 10:54

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_notifications_contributions_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_deadine',
            field=models.DateTimeField(validators=[backend_app.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('event', 'Event'), ('emergency', 'Emergency')], default='personal', max_length=20),
        ),
    ]
