# Generated by Django 5.1.6 on 2025-02-12 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_members_joined_date_alter_loans_loan_deadine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='loan_deadine',
            new_name='loan_deadline',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
