# Generated by Django 5.1.6 on 2025-02-12 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_rename_loan_deadine_loans_loan_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
