# Generated by Django 5.1.6 on 2025-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_alter_notifications_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification',
            field=models.CharField(default='Greetings, testing app', max_length=1000),
        ),
    ]
