# Generated by Django 5.1.6 on 2025-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
